import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'
import classNames from 'classnames'
import Header from '@components/Header'
import BreadCrumb from '@components/BreadCrumb'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: {
  children: ReactNode
}) => {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={classNames(inter.className, 'flex flex-col min-h-screen justify-between')} id='app-body'>
        <Header />
        <main id='main' className='mb-auto pt-[100px]'>
          <div className='p-4'>
            <BreadCrumb />
          </div>
          {children}
        </main>
        <footer
          data-testid='footer'
          className='relative p-4 text-sm border-solid border border-[#c4c4c4] border-x-0 border-b-0 md:flex md:items-center md:justify-between'
        >
          Footer
        </footer>
      </body>
    </html>
  )
}

export default RootLayout;