import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import classNames from 'classnames'
const poppins = Poppins({ weight: "500", subsets: ['devanagari'] })
import './globals.css'
import HeaderWrapper from '@components/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: {
  children: ReactNode
}) => {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type='image/x-icon' href="/favicon.ico" sizes="96x96" />
      </head>
      <body className={classNames(poppins.className, 'flex flex-col min-h-screen justify-between')} id='app-body'>
        <HeaderWrapper />
        <main id='login-main'>
          {children}
        </main>
        <footer
          data-testid='footer'
          className='relative p-4 text-sm border-solid border border-[#c4c4c4] border-x-0 border-b-0 md:flex md:items-center md:justify-between'
        >
          Footer
        </footer>
      </body>
    </html>
  )
}

export default RootLayout;